db.zips.aggregate([
   {
      "$match":{
         "$or":[
            {
               "state":"CA"
            },
            {
               "state":"NY"
            }
         ]
      }
   },
   {
      "$group":{
         "_id":{
            "city":"$city",
            "state":"$state"
         },
         "pop":{
            "$sum":"$pop"
         }
      }
   },
   {
      "$match":{
         "pop":{
            "$gt":25000
         }
      }
   },
   {
      "$group":{
         "_id":0,
         "avg_pop":{
            "$avg":"$pop"
         }
      }
   }
])